apiVersion: v1
kind: Service
metadata:
  name: payflow-service
  labels:
    app: payflow
spec:
  type: ClusterIP
  selector:
    app: payflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
